#!/bin/sh
# Travel Router - first boot setup
# This script runs once on first boot, then is deleted by OpenWrt.
# Generated by configure.sh — do not edit manually.

# ---- Enable PassWall (VPN transparent proxy) ----
/etc/init.d/passwall enable

# ---- Enable core services ----
/etc/init.d/dnsmasq enable
/etc/init.d/firewall enable

# ---- Create xray log directory ----
mkdir -p /var/log/xray

# ---- Ensure geo data is accessible to xray ----
# v2ray-geoip/geosite may install to /usr/share/v2ray/, xray expects /usr/share/xray/
if [ -d /usr/share/v2ray ] && [ ! -d /usr/share/xray ]; then
    ln -s /usr/share/v2ray /usr/share/xray
elif [ -d /usr/share/v2ray ] && [ -d /usr/share/xray ]; then
    cp -n /usr/share/v2ray/*.dat /usr/share/xray/ 2>/dev/null || true
fi

# ---- Set hostname and timezone ----
uci set system.@system[0].timezone='UTC0'
uci set system.@system[0].hostname='travel-router'
uci commit system

# ---- Configure WiFi AP ----
# Wait for CYW43455 SDIO radio to appear (up to 10 seconds)
n=0
while [ $n -lt 10 ] && [ ! -d /sys/class/ieee80211/phy0 ]; do
    sleep 1
    n=$((n + 1))
done

# Auto-detect radio hardware and generate wireless config
if [ -d /sys/class/ieee80211/phy0 ]; then
    wifi config

    # Configure radio0 (CYW43455 on RPi5) — 2.4GHz for max compatibility
    uci set wireless.radio0.band='2g'
    uci set wireless.radio0.channel='6'
    uci set wireless.radio0.htmode='HT20'
    uci set wireless.radio0.country='US'
    uci set wireless.radio0.cell_density='0'
    uci set wireless.radio0.disabled='0'

    # Configure the access point interface
    uci set wireless.default_radio0.device='radio0'
    uci set wireless.default_radio0.network='lan'
    uci set wireless.default_radio0.mode='ap'
    uci set wireless.default_radio0.ssid='@@WIFI_SSID@@'
    uci set wireless.default_radio0.encryption='psk2'
    uci set wireless.default_radio0.key='@@WIFI_PASSWORD@@'
    uci set wireless.default_radio0.ieee80211w='1'
    uci set wireless.default_radio0.disassoc_low_ack='0'
    uci set wireless.default_radio0.disabled='0'

    uci commit wireless
else
    logger -t travel-router "WARNING: WiFi radio not detected after 10s, skipping AP setup"
fi

# ---- Set root password (SSH access) ----
echo -e "@@ROOT_PASSWORD@@\n@@ROOT_PASSWORD@@" | passwd root 2>/dev/null || true

exit 0
