
# PassWall — generated by configure.sh (do not edit manually)
config global
	option enabled '1'
	option tcp_node 'node_primary'
	option udp_node 'node_primary'
	option tcp_proxy_mode '@@PROXY_MODE@@'
	option udp_proxy_mode '@@PROXY_MODE@@'
	option localhost_proxy '1'
	option close_log '0'
	option loglevel 'warning'

config global_haproxy
	option balancing_enable '0'

config global_delay
	option auto_on '0'
	option start_delay '1'

config global_forwarding
	option tcp_no_redir_ports 'disable'
	option udp_no_redir_ports 'disable'
	option tcp_redir_ports '1:65535'
	option udp_redir_ports '1:65535'
	option accept_icmp '0'
	option use_nft '1'
	option tcp_proxy_way 'tproxy'
	option ipv6_tproxy '0'

config global_other
	option nodes_ping 'auto_ping tcping'

config global_rules
	option auto_update '0'
	option chn_list 'default'
	option geoip_update '0'
	option geosite_update '0'
	option v2ray_location_asset '/usr/share/xray/'

config global_dns
	option dns_mode 'xray'
	option remote_dns '1.1.1.1'
	option remote_dns_protocol 'tcp'
	option remote_fakedns '0'
	option dns_cache '1'

config global_autoswitch
	option enable '@@AUTOSWITCH_ENABLE@@'
	option testing_time '30'
	option connect_timeout '3'
	option retry_num '3'
	option restore_switch '1'
	option restore_switch_time '300'

# Primary server
config nodes 'node_primary'
	option remarks 'Primary - @@VPN_PRIMARY_REMARKS@@'
	option type 'Xray'
	option protocol 'vless'
	option address '@@VPN_SERVER_ADDRESS@@'
	option port '@@VPN_SERVER_PORT@@'
	option uuid '@@VPN_UUID@@'
	option flow '@@VPN_PRIMARY_FLOW@@'
@@VPN_PRIMARY_TRANSPORT@@
	option tls '1'
	option reality '1'
	option reality_publicKey '@@VPN_REALITY_PUBLIC_KEY@@'
	option reality_shortId '@@VPN_REALITY_SHORT_ID@@'
	option reality_serverName '@@VPN_REALITY_SNI@@'
	option reality_fingerprint 'chrome'
	option tls_serverName '@@VPN_REALITY_SNI@@'
	option fingerprint 'chrome'

@@BACKUP_NODE@@

config global_subscribe
	option auto_update '0'

@@AUTOSWITCH_SECTION@@
